version: "3.7"

services:
  bot:
    image: fedora:latest
    volumes:
      - ./dist:/bot
    security_opt:
      - label:disable
    restart: always

  db:
    image: postgres:latest
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: UsmanAga
      POSTGRES_PASSWORD: AdMiNpAsSwOrD
      POSTGRES_ROOT_PASSWORD: RoOtPaSsWoRd
      POSTGRES_DB: BotDB
    security_opt:
      - label:disable
    restart: always