#? type
type: postgres

#? host
host: localhost

#? port
port: 5432

#? username
username: usmanagabot

#? password
password: usmanagabot

#? database
database: usmanagabot

#? options
synchronize: true
logging: true